# Generated by Django 3.0.7 on 2020-06-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_auto_20200617_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_count',
            field=models.IntegerField(default=0),
        ),
    ]
